"""Initial ClickTodo schema

Revision ID: bd3131f2fc1d
Revises: 49b72ed675d4
Create Date: 2025-04-14 19:35:48.992433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3131f2fc1d'
down_revision = '49b72ed675d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_name')
        batch_op.drop_column('password')
        batch_op.drop_column('email_confirmed_at')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('password_hash')

    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
